spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://${MYSQLHOST:ballast.proxy.rlwy.net}:${MYSQLPORT:31618}/${MYSQLDATABASE:railway}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${MYSQLUSER:root}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${MYSQLPASSWORD:}}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.port=${PORT:8080}

